config/routes.rb
Rails.application.routes.draw do
  
  resources :categories, except: [:destroy]
  resources :users
  
  get 'signup', to: 'users#new'
  
  
  resources :articles
  
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  

  

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container" align="center">
    <small>
      Copyright &copy; <a href="http://gaadvising.com">Global Advisng</a>
    </small>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a id="logo" class="navbar-brand" href="#">Alpha Blog</a>-->
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |c| %>
              <li> <%= link_to "#{c.name}", c %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %>'s Profile <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>    
          </ul>
        </li>
        <% else %>
          <li><%= link_to 'Log In', login_path%></li>
          <li><%= link_to 'Sign Up', signup_path%></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation'%>

<p align="center">
  <%= flash unless flash.blank? %>
</p>

<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer'%>

</body>
</html>